"""Add itinerary and cost fields to Trip model

Revision ID: 647795ba1cc1
Revises: a34bafdb7744
Create Date: 2025-11-18 11:25:06.194219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647795ba1cc1'
down_revision = 'a34bafdb7744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itinerary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('itinerary')

    # ### end Alembic commands ###
