"""Add budget breakdown fields to Trip

Revision ID: a34bafdb7744
Revises: e7a8f8c0b762
Create Date: 2025-11-17 17:59:35.552105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34bafdb7744'
down_revision = 'e7a8f8c0b762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('food_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transport_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('travel_cost_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('distance_km', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_local', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('is_local')
        batch_op.drop_column('distance_km')
        batch_op.drop_column('travel_cost_usd')
        batch_op.drop_column('transport_usd')
        batch_op.drop_column('food_usd')
        batch_op.drop_column('hotel_usd')

    # ### end Alembic commands ###
