"""Add budget_level column to Trip

Revision ID: e7a8f8c0b762
Revises: 
Create Date: 2025-11-14 12:43:54.315604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a8f8c0b762'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_level', sa.String(length=20), nullable=False, server_default='mid'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('budget_level')

    # ### end Alembic commands ###
