"""Add travel_tips column to Trip

Revision ID: fbfac9b2a078
Revises: 2bdb6f6c1014
Create Date: 2025-11-20 11:08:10.948282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfac9b2a078'
down_revision = '2bdb6f6c1014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('travel_tips', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('travel_tips')

    # ### end Alembic commands ###
